export const images = [
    {id: 1, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 2, img: './images/02-spitzer-smc.jpg'},
    {id: 3, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 4, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 5, img: './images/1_janapanfilova.jpg'},
    {id: 6, img: './images/2_ivanbertusi-raindropletscountryside.jpg'},
    {id: 7, img: './images/3_brianlaiphotography-waterfall4.jpg'},
    {id: 8, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 9, img: './images/02-spitzer-smc.jpg'},
    {id: 10, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 11, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 12, img: './images/1_janapanfilova.jpg'},
    {id: 13, img: './images/2_ivanbertusi-raindropletscountryside.jpg'},
    {id: 14, img: './images/3_brianlaiphotography-waterfall4.jpg'},
    {id: 15, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 16, img: './images/02-spitzer-smc.jpg'},
    {id: 17, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 18, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 19, img: './images/1_janapanfilova.jpg'},
    {id: 20, img: './images/2_ivanbertusi-raindropletscountryside.jpg'},
    {id: 21, img: './images/3_brianlaiphotography-waterfall4.jpg'},
    {id: 22, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 23, img: './images/02-spitzer-smc.jpg'},
    {id: 24, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 25, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 26, img: './images/1_janapanfilova.jpg'},
    {id: 27, img: './images/2_ivanbertusi-raindropletscountryside.jpg'},
    {id: 28, img: './images/3_brianlaiphotography-waterfall4.jpg'},
    {id: 29, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 30, img: './images/02-spitzer-smc.jpg'},
    {id: 31, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 32, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 33, img: './images/1_janapanfilova.jpg'},
    {id: 34, img: './images/2_ivanbertusi-raindropletscountryside.jpg'},
    {id: 35, img: './images/3_brianlaiphotography-waterfall4.jpg'},
    {id: 36, img: './images/01-spitzer-omeganebula.jpg'},
    {id: 37, img: './images/02-spitzer-smc.jpg'},
    {id: 38, img: './images/03-spitzer-w5nebula.jpg'},
    {id: 39, img: './images/04-spitzer-helixnebula.jpg'},
    {id: 40, img: './images/1_janapanfilova.jpg'},
]

export const gallery = document.querySelector('.gallery')
export const galleryZoom = document.querySelector('.gallery-zoom')
